### ISSUE TITLE
Add Extended Field Support

### ISSUE THREAD

**Issue by jwalgran** [open-apparel-registry/open-apparel-registry#1585]
# Task 026-A -  Extended Profile - Add Fields
## (1) Contributors can submit to data staging and see extended fields in API responses and the webside sidebar
January 20 - February 2, 2022
- [x]  :one: #1581 
- [x]  :five: #1582 
- [x]  :two: #1584 
- [x]  :one: #1586 
- [x]  :three: #1583 

February 3 - February 16, 2022
- [x]  1️⃣ #1618 (NOTE: This issue was added after the initial creation of the checklist)
- [x] :one: #1570
- [x] :three: #1540 

##  (2)
- [x] #1592 (formerly 3)
- [x] **CHECKPOINT 1** OAR has first group of stakeholders, including API users, upload and test the data on staging
- [x] **CHECKPOINT 2** February 8: OAR can show EM (on staging) to current customers so they know what changes to expect
- [x] February 10: OAR provides taxonomy feedback
- [x] February 11: OAR provides feedback from users

February 17 - March 2, 2022
- [x] #1623 
    - [x] :one: #1634
    - [x] :two: #1655
    - [x] :one: #1653
    - [x] 2️⃣ : #1638
- [x] :two: #1541 
- [x] :two: #1590 
    - [x] :two: #1648 
    - [x] :two: #1649
    - [x] :one: #1669 (added 2022-02-23)
- [x] :three: #1591 

# Task 016 - Search by additional fields
- [x]  :two: #1587 

March 3 - March 16, 2022
- [x] **CHECKPOINT 3** March 3: Everything is on production except for search. Test users & API users can upload to production and receive query results. The sidebar remains switched off (prior to official launch).
- [x] :two: #1562 
- [x] :one: #1588 
- [x] :five: #1589 

# Misc - Task 26
- [x] :two: #1689
- [x] :one: #1690
- [x] :two: #1703
- [x] :one: #1443
- [x] :one: #1706
- [x] :two: #1711

**March 17th Sprint**
- [x] :two: #1561
- [x] :one: #1704
- [x] :one: #1707

**Comment by TaiWilkin** [comment]
Discuss: how do we handle search for extended fields when in embed mode - do we ignore extended field values submitted by other contributors?
