### ISSUE TITLE
OSHub Production Release Epic

### ISSUE THREAD

**Issue by TaiWilkin** [open-apparel-registry/open-apparel-registry#2177]
Production Release Timeline

Before October 14th
- [x] #2088 (Embedded map behavior) - prep
- [x] #1893 (Set up OS Hub production site)
    - [x] #1976
        - [x] #1978
- [x] Rehearse on OAR staging #2160 Application Changes (note: don't run System Changes yet)
  - Notify the OAR team in #oar-management that we will be testing read-only on OAR staging
  - Create a branch based from `ms/oar-read-only-updates`  named `test/oar-read-only-updates` and push it to Github. CI  will deploy the branch to OAR staging
  - Run the System Changes on the OAR staging database
  - Test all features. Coordinate with the OS Hub team on #oar-management to also test.
  - When testing is complete, trigger a build of the `develop` branch in CI to restore OAR staging 
- [x] #1927 (Run merge moderation script)
- [x] #2183 (Update info.openapparel.org links for OSHub)
- [x] #2208 

*  **NOTE** Performance issues on staging. This will not be included in the release.  #2199

On October 14th
- [x] 1. Ensure the OS Hub production `gunicorn_worker_timeout` and `app_ecs_grace_period_seconds` tfvars match OAR production values
- [x]  2. Release the latest OS Hub branch to production
- [x]  3. Deploy the new release  #2198
- [x]  4. Notify OS Hub team that migration is in process and provide expected completion time (based on rehearsal) 
- [x]  5. Final OAR release, including #2160, and  System Changes
- [x]  6. ~#1894 (Migrate data to new site)~
- [x]  7. Notify OS Hub team that data migration is finished

Before November 1st
- [x] #2275 
- [x] #2274
- [x] #2277
- [x] #2273
  - **NOTE** preparing this can start before launch day but the A record cannot be set up until we switch to the real production domain name
- [x] Establish domain name contact for launch day
    - The Azavea systems account has access to the domain configuration. Tyler can provide additional support.

On November 1st
1. [x] #2278
2. [x] #2185
3. [x] #2273
4. [x] #2149 
5. [x] Update UptimeRobot to monitor the real production domain
6. [x]  #1895 (Redirect to new URL)
