### ISSUE TITLE
UI improvements for confirming/denying matches

### ISSUE THREAD

**Issue by dboyer** [open-apparel-registry/open-apparel-registry#482]
## Overview

There are several design elements of the match confirmation process that could be improved. 

### Is your feature request related to a problem? Please describe.

The UI for confirming/denying matches lacks a few key features. 

### Describe the solution you'd like

This list will likely change but should include:

- [ ] List number of facilities that fall within each status (matched, etc)

- [ ] Add search options

- [ ] Add filter options

### Additional Context

Work with the UX team on these tasks.
